### ISSUE TITLE
Clearing the GPU Memory

### ISSUE THREAD

**Issue by CirilBohak** [CirilBohak/Neck_Veins#2]
When loading new model into the GPU, sometimes some parts of old model are still rendering. I believe this might be the issue with not clearing the GPU memory at the initialisation of shaders (probably the OpenCL shaders).

Are there zeros written in the memory at the beginning? I think this might be the issue. Since the memory is not properly initialised.

**Comment by asodja** [comment]
Any tips how to reproduce this bug?

**Comment by CirilBohak** [comment]
Try loading different models one after another. Sometimes you get parts of previous model in empty space of the new model.
